flag_management:
  individual_flags:
    - name: Packages
      paths: 
      - packages/kocoa 
      carryforward: true
    - name: Samples
      paths: 
      - samples/kocoa-tutorial
      carryforward: true