flag_management:
  individual_flags:
    - name: kocoa
      paths:
        - packages/kocoa 
      carryforward: true
    - name: '@kocoa/core'
      paths:
        - packages/kocoa-core
      carryforward: true
    - name: '@kocoa/adapter-mocha'
      paths:
        - packages/kocoa-adapter-mocha
      carryforward: true
    - name: semantic-release-rush-dependency-version
      paths:
        - packages/semantic-release-rush-dependency-version 
      carryforward: true
    - name: Samples
      paths:
        - samples/kocoa-tutorial
      carryforward: true