flag_management:
  individual_flags:
    - name: latte-latte
      paths: 
      - apps/latte 
      carryforward: true
    - name: latte-tutorial
      paths: 
      - samples/latte-tutorial
      carryforward: true