flag_management:
  individual_flags:
    - name: latte  #fill in your own flag name
      paths: 
      - projects/latte  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
    - name: samples #fill in your own flag name
      paths: 
      - projects/latte-samples  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true