flag_management:
  individual_flags:
    - name: Apps
      paths: 
      - apps/kocoa 
      carryforward: true
    - name: Samples
      paths: 
      - samples/kocoa-tutorial
      carryforward: true