flag_management:
  individual_flags:
    - name: apps
      paths: 
      - apps/latte 
      carryforward: true
    - name: samples
      paths: 
      - samples/latte-tutorial
      carryforward: true