name: 'Setup Rush'
description: 'Setup Rush environment'
runs:
  using: "composite"
  steps:
    - name: Cache Rush
      uses: actions/cache@v3
      with:
        path: |
          common/temp/install-run
          ~/.rush
        key: ${{ runner.os }}-${{ hashFiles('rush.json') }}
    - name: Cache PNPM dependencies
      uses: actions/cache@v3
      with:
        path: ./common/temp/pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install Rush
      shell: bash
      run: node common/scripts/install-run-rush.js install