name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Build projects
        run: node common/scripts/install-run-rush.js build
      - name: Archive build folders
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            apps/*/build/**
            samples/*/build/**

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Check lint
        run: node common/scripts/install-run-rush.js lint

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: ['12', '14', '16', '18']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download builds
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Run tests
        run: node common/scripts/install-run-rush.js test -v

  test-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download builds
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Run tests with coverage
        run: node common/scripts/install-run-rush.js test:coverage -v
      - name: Upload code coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: |
            apps/*/coverage/**
            samples/*/coverage/**

  codeCov:
    needs: test-coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: apps/latte
            flag: latte-latte
          - project: samples/latte-tutorial
            flag: latte-tutorial
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download code coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
      - name: Upload code coverage reports
        uses: codecov/codecov-action@v2
        with:
          directory: ./${{ matrix.project }}/coverage
          flags: "${{ matrix.flag }}"

  sonarcloud:
    needs: test-coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download code coverage artifacts
      uses: actions/download-artifact@v3
      with:
        name: code-coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}