name: Node CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Build projects
        run: node common/scripts/install-run-rush.js build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            packages/*/build/**
            samples/*/build/**

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Check lint
        run: node common/scripts/install-run-rush.js lint

  test:
    name: Node ${{ matrix.node }} - ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: ['14', '16', '18']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Run tests
        run: node common/scripts/install-run-rush.js test -v

  test-coverage:
    name: Generate code coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download builds
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Run tests with coverage
        run: node common/scripts/install-run-rush.js test:coverage -v
      - name: Upload code coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: |
            packages/*/coverage/**
            samples/*/coverage/**

  codeCov:
    name: Upload ${{ matrix.flag }} coverage
    needs: test-coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: packages/kocoa
            flag: kocoa
          - directory: packages/kocoa-core
            flag: '@kocoa/core'
          - directory: packages/kocoa-adapter-mocha
            flag: '@kocoa/adapter-mocha'
          - directory: samples
            flag: Samples
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download code coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
      - name: Upload code coverage reports
        uses: codecov/codecov-action@v2
        with:
          directory: ./${{ matrix.directory }}/
          flags: "${{ matrix.flag }}"

  sonarcloud:
    name: Sonarcloud
    needs: test-coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download code coverage artifacts
      uses: actions/download-artifact@v3
      with:
        name: code-coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}