name: Release

on:
  push:
    branches: '**'

jobs:
  release:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: changed-files
      - name: Get packages list
        run: |
          projects=(cat ./rush.json | jq '.projects[].projectFolder')
          echo "${projects}"
      