name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Build packages
        run: node common/scripts/install-run-rush.js build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./**/build/**
            !./**/node_modules/**/build/**

  release:
    name: Publish packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup Rush
        uses: ./.github/actions/rush
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node common/scripts/install-run-rush.js release -v